spring.application.name=notification-kafka-demo


# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/notificationdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hariprasad!03
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# In Boot 4/Hibernate 7, 'update' is fine for dev,
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DIALECT: You can usually DELETE this line in Boot 4.

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===================================================================
# Kafka Core Connection Setup
# ===================================================================
# Points to your local Kafka cluster broker. Update this string if
# deploying to production or Dockerized environments (e.g., kafka:9092)
spring.kafka.bootstrap-servers=localhost:9092

# ===================================================================
# Framework Safety Controls
# ===================================================================
# Disables Spring Boot's default auto-configured JSON mapping properties
# to guarantee that our custom configuration classes (like trusted package lists
# and explicitly handled Type Headers) take absolute priority.
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ===================================================================
# Logging Profiles (Recommended for Debugging Practice Projects)
# ===================================================================
# Enables clear internal framework log tracking for monitoring connections,
# rebalances, and partition assignments in the console window.
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO
logging.level.com.example.notificationservice=DEBUG